version: "2"
services:
  portainer:
    image: portainer/portainer
    command: --no-auth
    volumes:
      - ./data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:9000
